### ISSUE TITLE
[Feature Request] Rich Presence for DiscordPtb

### ISSUE THREAD

**Issue by binarynoise** [maximmax42/Discord-CustomRP#11]
It would be really cool, if you could target the DiscordPtb running along the normal Discord instead of Discord.
I use the two instances to use two accounts and I want the Rich Presence to show up on the second (Ptb) account.

Is that possible?

**Comment by maximmax42** [comment]
If you want the status to show up only on one account, then try to launch the respective client before the other one, as CustomRP will connect to the client that has launched earlier.
If you want to have status on both, well... I don't know of a good way to implement that, because it would have to either ask user for how many clients are running, or detect it automatically, and then multiple connections would be quite a pain to manage, so I don't know.

**Comment by binarynoise** [comment]
Yes, starting the second Discord before the first, then connect the Custom Presence and finally launch the main Discord does work. Thank you.
