### ISSUE TITLE
Minimize

### ISSUE THREAD

**Issue by ilmunti** [maximmax42/Discord-CustomRP#155]
I don't want the application to be sitting on my desktop, why isn't there a button for it? if there is a minimize button then you guys must go to design school or something.

**Comment by maximmax42** [comment]
It minimizes to tray when you press x. Also I'm a single dev. Also if you have a suggestion on how to make it more user friendly, I'm all ears.

**Comment by ilmunti** [comment]
add a - button where it minimizes, i didn't know at all tbh. would be
easier you know.

**Comment by maximmax42** [comment]
_ button is used in 99.9% of apps to minimize to taskbar, not tray. Using it like that would be breaking all UI conventions, can't say it would be a good experience.

X button on the other hand is always used to close the app or window. If the app closes permanently with X, it usually asks "Do you want to quit/save?", and apps that hide to tray either notify the user about that (which is what I do), or just silently hide.

I don't think I can change X's tooltip, since it's a Windows thing.

**Comment by tylerkade** [comment]
The program tells you that it doesn't close upon pressing the x button.
There is also the option to have the program start minimised in settings, this seems like a non-issue to me.

**Comment by ilmunti** [comment]
Thanks for the tip!
