### ISSUE TITLE
Windows Defender/Virus Total alert

### ISSUE THREAD

**Issue by nefarius** [maximmax42/Discord-CustomRP#2]
Greetings!

I've cloned, inspected, built and run your project from sources just fine, unfortunately the latest executable release you offer is flagged by Windows Defender and [Virus Total](https://www.virustotal.com/gui/file/4f8a3d785643516971fd24e79dc20ad51aa4604a0ac4cda5b62ce7758e079f50/detection).

# Windows Defender warning

![image](https://user-images.githubusercontent.com/286631/63093018-eff52a00-bf63-11e9-9e98-878071ef8a99.png)

# PE analysis details

![image](https://user-images.githubusercontent.com/286631/63093140-55e1b180-bf64-11e9-8fa0-ba2df7498cc1.png)

![image](https://user-images.githubusercontent.com/286631/63093145-58dca200-bf64-11e9-98f1-a6827394481f.png)

![image](https://user-images.githubusercontent.com/286631/63093148-5bd79280-bf64-11e9-9d9f-f18d467c53c7.png)

Are you possibly using some wonky, fairly unknown executable packer/compressor that's flagged here?

Cheers

**Comment by maximmax42** [comment]
Hello!

That's curious. [Scanning from a direct URL](https://www.virustotal.com/gui/url/e816a828515bcf8da8240e933b72947e2145cc982877990d5a5ea072e2be03c3/detection) gives 0 results, but downloading and scanning like that indeed gives 10 results. But the .zip is [clean](https://www.virustotal.com/gui/file/e36a29aa37719306dc6c9eaf845460f27f94d0c3cacaee40f4f4f19a57899119/detection).

For packing up files I use WinRAR's self-extracting archive which unpacks everything into `%appdata%\CustomRP` and makes a link on user's desktop. Perhaps it triggers because some viruses use self-extracting archives? Or maybe because it doesn't ask anything before extracting.

In any case, more than sure it's a false-positive, but I'll look into other methods of installing. Thank you for notifying!

**Comment by nefarius** [comment]
This is so weird. Our two different scan methods claim to be the same hash, yet when I download und upload the binary I get different results:

![image](https://user-images.githubusercontent.com/286631/63096894-5cc1f180-bf6f-11e9-91e8-710f0567d600.png)

![image](https://user-images.githubusercontent.com/286631/63096907-63e8ff80-bf6f-11e9-83dd-d45d9d15fa6a.png)

Self-extractors are common for almost decades now though, and I assume false-positive as well.

If you download the same binary from GitHub and open it in [pestudio](https://winitor.com/get.html) as I did, does it also claim 9 hits on Virus Total? Maybe it's a regional thing 😛 

Cheers

PS: love the tool btw. 👍

**Comment by maximmax42** [comment]
I assume VirusTotal's URL scanning and file scanning use different engines.

Yeah, I downloaded the executable and uploaded it directly to VirusTotal. 

And thank you! Do you have any suggestions, by the way?

**Comment by nefarius** [comment]
Uh, so far it's doing exactly what I was looking for; implementing a workaround for a status message since a lot of my contacts have Discord only and sometimes just DND or Available status doesn't quite cut it 😃 

I'm sure to report back once something pops up though 😉 

Cheers
