### ISSUE TITLE
!MALWARE! (in the popup ad on the website)

### ISSUE THREAD

**Issue by Env-Ir0n** [maximmax42/Discord-CustomRP#239]
After installing and running the program I get sent to a fraudulent webpage [here](https://s3.ap-southeast-2.amazonaws.com/72261.6lkjko.9869.8403.97bui.063l.l4b5.kgrwbtp.9gj.5sx.maee/07o07o07p07+(1)/index.html267#)

**To Reproduce**
Install the exe from the website
Run the program
Open a web browser of choice
Get fake windows defender website

!! NOTE !! This may make it so you can't exit the page, use task manager to quit the browser AND CustomRP

**Expected behavior**
Not send me to a phishing site

**Useful Info**
 - Windows Version: [Windows 11]
 - Application Version: [Latest as of report]

**Additional context**
The fraud site has been reported to AWS and my countries anti-fraud agencies. If this is your site, remove it and the malicious code immediately 
local police will be notified when the site is tracked down.

**Comment by maximmax42** [comment]
When you press the download button on the site, the installer file starts to download (named CustomRP.[version].exe, where [version] is of format 1.2.3), and a popup ad opens up, which you should be able to just close. Most of the time, as far as I know (because I very rarely get reports like yours), the popup ads are safe, but sometimes malicious actors put up fake tech support ads, like the one you got.

**My website and the app themselves contain no malware.** But if you downloaded something else from the popup ad, it could contain malware.
I'm not in charge of what ads gets shown to who, my ad network [Adsterra](https://adsterra.com) is.

What I recommend you do to is 1) run [AdwCleaner](https://malwarebytes.com/adwcleaner/) and your antivirus scan, 2) report abusive ad's URL (not CustomRP's URL) to Adsterra ("Report Abuse" button on the bottom right of their website).

**Comment by maximmax42** [comment]
Also, the malicious URL you've sent seems to have already been marked as malicious by Google. Because the email about this issue went to my spam folder, and not to my inbox.

**Comment by Env-Ir0n** [comment]
Ah, I see. The site has probably been blocked as I reported it. This issue is now closed. Thank you for your comment
